name: Trivy Vulnerability Scan
on:
  workflow_dispatch:
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
        tar zxvf trivy_Linux-64bit.tar.gz
        sudo mv trivy /usr/local/bin/

    - name: Scan base image
      run: trivy image --severity HIGH,CRITICAL --no-progress ubuntu:22.04

    - name: Scan local files (optional)
      run: trivy fs --severity HIGH,CRITICAL --no-progress 

